### ISSUE TITLE
Opinion → Problem change leaves some issues weirdly tagged.

### ISSUE THREAD

**Issue by Viech** [Unvanquished/gameplay#12]
#7 and #8 are really just opinions and don't describe a problem in a strict sense. How to deal with that @Gireen?

**Comment by Gireen** [comment]
I think they are more like ideas than problems. 
#8 is a idea without concrete problem to solve.

#7 is also an idea ( have stronger knockback for luci ) and problem ( luci jumps are hard to do )
Small problems are a bit of a grey area if a solution for a problem is just doing the opposite or said problem.

**Comment by Viech** [comment]
#8 really is more of an opinion though, it doesn't specify how exactly turrets should be stronger or weaker in the respective situations.

Giving #7 and similar small balance tweak suggestion the idea status also doesn't feel right because one could post a really nice idea that's worth keeping around for a month or two while someone else can have the "idea" to _give dretches +5 HP_ which is really just the perceived problem that dretches die to easily combined with a very specific solution proposal.

Could we have both "opinion" and "problem" tags, same color and same rules just different wording?

**Comment by Gireen** [comment]
i mean every idea leaves room for interpretation what problem it can solve or suggests to solves. Without a agreed upon problem mentioned in it that it can solve all ideas should treated as just ideas and how they could impact the gameplay. 

We could add a "promising" tag or something for ideas that would exclude them from timelimits even if they have no related problem.

To use your example the idea "dretch +5 hp" is a valid idea. It would probably closed after the timelimit, since it is a really simple idea.

**Comment by mjstahlberg** [comment]
I've revisited both #7 and #8 and I don't recall many later issues where an "opinion" tag would've been useful.
