### ISSUE TITLE
Aliens actively defending their base are too vulnerable when humans have already entered.

### ISSUE THREAD

**Issue by Stooberton** [Unvanquished/gameplay#2]
1) Aliens cannot evolve when humans are nearby, leaving them stuck as dretches and unable to effectively defend the base/outpost. Possible solution here would be to allow aliens to evolve when nearby the overmind all the time, even with humans nearby. Grangers often cannot switch to a dretch and assist in defending the base when humans are nearby. Humans, conversely, can switch back and forth from combat/builder at any time while _also_ healing faster than aliens.
2) Aliens spawn automatically at the closest egg, even if there are humans very close by, this almost always results in a respawned player dying instantly. This applies to humans too, neither should work with enemies nearby if there are other spawns available OR the nearest egg is near the overmind.
3) Aliens heal extremely slowly, much slower than humans, even inside their own base. It is _extremely easy_ to run inside an alien base as a human, kill the alien, and run out.  Any alien that defends their base can only do so once before they have to heal for upwards of 30 seconds. This would be fixed by something like the Overmind always providing the healing of a booster.

**Comment by Viech** [comment]
This issue is on the verge of being too broadly scoped but I think I can reword the title so that we have a basis for discussion…

**Comment by Viech** [comment]
I do not agree with the notion that I have changed the title to. I think that it would be frustrating for attackers not to deal damage when they have made it into the enemy base. I'd like both teams to have a good reason to stop attackers already outside their base, which counters boring defensive strategies (base camping).

**Comment by Viech** [comment]
This being flagged as controversial just means that we didn't agree upon the key opinion posed in this issue (as I understand it) in full. However some of the more particular opinions/problems discussed here could potentially be agreed upon independently for being individually problematic or unfun, so feel free to open additional issues where you talk about any of your three original points.

**Comment by Gireen** [comment]
> Aliens actively defending their base are too vulnerable when humans have already entered

I would say yes to this. 
Even in broader sense. Small and injured aliens can't effectively defend there base. 
Compared to humans where everyone can deal damage to attackers from  a safe distance. With stage or cash differences this problem becomes even worse.

**Comment by Viech** [comment]
But isn't the problem rather that humans can defend so well? One human camping on a medipad next to the armory with a ranged weapon can be frustrating to aliens even in the absence of good defensive structures. Do you want similar defense strength for aliens? I'd rather have two teams that are encouraged to be playing the map to prevent enemies from entering their base and I feel aliens are fine in that regard, they really don't want to fight alongside their base defenses and that's a good thing in my opinion.

**Comment by Gireen** [comment]
This boils down to the question should a normal base with defense structures be a save place for a team? And only attackable by enemys after the defense is weakened?
I think yes. For humans this is barely reached but not for aliens.
If building defense has no influence on the base safety does it have any meaning at all? 
That is more frustrating than encouraging.

**Comment by Viech** [comment]
Defenses should make a difference, of course. But you should rarely, if at all, feel more comfortable letting the enemy inside your base than stopping them outside your base. For aliens this is true: No matter how much defense you have going, you will lose some structures if the enemy isn't prevented from going in. That's good in my opinion.

For humans we should be aware that they need stronger defenses because of their limited mobility; they can't always defend or stop aliens rushing past them. Still they should not be incentivized to _stay in their base_ and wait for aliens to come, which I feel they currently are much more than aliens. My take would thus rather be: "Humans actively defending their base from within add too much defensive strength." Balance wise this goes in the same direction but it asks for different solutions.

**Comment by Gireen** [comment]
> No matter how much defense you have going, you will lose some structures if the enemy isn't prevented from going in. That's good in my opinion.

Some. That's the point. Humans are only limited by ammo and the time it takes for aliens to kill them. Witch in the worst case lets them destroy many if not all buildings, cause 

>  they can't always defend or stop aliens rushing past them

Thats also true for aliens.

**Comment by bmorel** [comment]
> 3. Aliens heal extremely slowly

This received a fix [here](https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/commit/c1dbbf36ec480c637a84c546c0fe6d345c0baedb).

This leads us to having only 2. which received dedicated issues:

* #5 
* [#1232](https://github.com/Unvanquished/Unvanquished/issues/1232) "Make it possible to select spawn point"

So I believe this particular issue can be closed, since 2 of the 3 points have been addressed, and the last one have agreed upon fixes, they "only" need to be implemented.
