### ISSUE TITLE
[Idea] make drills resupply energy weapons

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/gameplay#33]
Related Problem issues: None, or maybe the fact humans should be encouraged to attack more

Currently, energy weapons have no real difference compared with kinetic or heat ones. In tremulous, their advantage were that:

1. a backpack could give more ammo
2. they could be resupplied on repeaters

I think it would be interesting to see how it goes if drills, which have more or less taken the repeater's role, would have the energy resupply feature.
It might be equally interesting to thus switch the mass driver as an energy weapon, considering the fact this particular weapon have low ammo stock.

**Disclaimer**
>Ideas without a related problem issue and lacking explanation or depth are closed after a certain time.

**Comment by Viech** [comment]
It's a _mass_ driver though. :)

No objections to making the Drill refill.

**Comment by DolceTriade** [comment]
Seems reasonable.

**Comment by superdupont-fr** [comment]
I think, a delay (like loading the Lucy) should be added. For Armory too.
Because, in this case, you can stay near RC and fire in continuous wuth Pulse Rifle or Laser gun.

I think, ammunition need to be paid. May be only SMG ammunition can stay free.
It's not a same problem.

Why not, resupply energy weapons on Drills need energy, and this can make lake of energy for building nearby if it's near the limit of capacity of the drill? And, why not only one fighter can resupply at once?

**Comment by bmorel** [comment]
> I think, a delay (like loading the Lucy) should be added. For Armory too.

This is a different issue. Please stay on-topic. If you have ideas, feel free to open new issue in this repo (and I'm not against the idea that equipping should take time, but still, out of topic)

**Comment by illwieckz** [comment]
Ah, I missed this issue. I'm 100% in favor of that.

- We removed repeater after having added drill, and drill somewhat replaces the repeater in that we need to build drills to build forward bases like we needed repeaters to do so (so forward base usually have drills).
- Energy weapons like lasgun has no decisive advantage over free machinegun if it's needed to return to main base (rc or amoury) to reload. If drills can reload a lasgun, then lasgun becomes a uninterrupted firing machine that can reload on every forward base, so it starts to have some decisive advantage despite its low damage. This also enables strategy to encourage people to buy weapons energy (then to spend personal credit) to save build points by not building armouries in forward bases.
- Removing the drill without giving another buildable the ability to reload energy weapons in forward bases looks like a regression I doubt this gameplay change was intentionnal (we probably just removed the repeater because it was not needed anymore to build forward base, forgetting it was also used to reload energy weapons). And drill is the best candidate for a replacement for such reload mechanism.
- The drill looks like a tiny reactor and if I'm right that's on purpose. Well, the drill uses the repeater model used as repeater before we remove repeater because it was nicer than the drill model, but then I still see the drill as a repeater replacement.

**Comment by bmorel** [comment]
Please review the one-line patch that solves this then: https://github.com/Unvanquished/Unvanquished/pull/1856

**Comment by bmorel** [comment]
Note that the mass driver is still not an energy weapon, which is a change from tremulous. I know unv is not tremulous, but this had to be said :)

**Comment by illwieckz** [comment]
Welp, I'm not sure I agree with mass driver not being an energy weapon anyway.

**Comment by bmorel** [comment]
Me neither, considering it's mechanics, it's important to be able to refuel it easily. Still, this is a different issue, and a one-line change, again.
