### ISSUE TITLE
[Problem] rockets are a lot more dangerous than hives

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/gameplay#34]
In current status (0.52.1 and the master branch as of 2022/01/29) rocket pods are much more dangerous than hives.
This would not be a problem if their cost was set according, but they are not.

Compared to rockets,  hives:

* have doubled damages
* regenerates 2 times faster
* cost 2 more BPs
* fires 3 times less (3s between each launch, versus 1s for rocket pods, but I admit I have some doubts on this one, the code is not very clear about it)
* takes twice the time to build
* have half the HP (125 vs 250)
* missiles are 3 times slower
* missiles do not explodes

**Disclaimer**
>All problems issues are treated as opinions until agree upon

**Comment by slipher** [comment]
Human bases are supposed to be more dangerous because of humans' lesser mobility, so it doesn't sound like a problem to me.

**Comment by bmorel** [comment]
Considering the fact humans can fly and are pretty fast, I kind of disagree on the "lack of mobility". Notably, the hive's missiles are as fast than a walking human, which means you can dodge them without even noticing there was a hive. You won't do that with rockets.
Also, rocket pods are stage 1, while hives are stage 3. Stage 3 for humans is medium armor unlocked. Hives damages (which are already 3 times under rockets, and ~27DpS) then becomes a lot weaker (8DpS).

I should probably edit the OP, since I forgot to mention that stage difference.

**Comment by Viech** [comment]
Rocket pods being stronger than hives is not a problem as such, since teams are strongly asymmetric. Apart from the movement difference mentioned that makes it easier for aliens to enter the human base than vice versa (despite the jetpack, which does indeed offset this), humans that do enter the alien base have to deal with limited ammo, reloads and low anti-structure damage with half of their weapons, while defenders are usually quick to react since they have high mobility on all classes plus a wallhack. I would say that humans have a lot of useful tools to make up for this and stronger base defense structures are certainly one of them.

If you find that the hive in particular is too weak or niche, that would be a better problem to discuss in my opinion.

**Comment by bmorel** [comment]
> Rocket pods being stronger than hives is not a problem as such, since teams are strongly asymmetric. Apart from the movement difference mentioned that makes it easier for aliens to enter the human base than vice versa (despite the jetpack, which does indeed offset this),

It has to be mentioned that the speed thing is also wrong for tyrants, and that dragoons are a lot less nimble than humans due to their size (and are barely faster than a running human).

> humans that do enter the alien base have to deal with limited ammo,

This might have been true in tremulous, but considering the amount of ammo there is in unv, it is pretty rare to end without ammo

> reloads

Chaingun, flamer, painsaw, lasgun, lucifer do not need reloads.
SMG, shotgun, mass driver, pulse rifle needs reloads.

3 weapons out of 8 indeed need reload. On the other side, advanced dragoon also needs a kind of reload.

> and low anti-structure damage with half of their weapons,

I'm curious here, could you elaborate on that "low anti-structure damage" thingy?

> while defenders are usually quick to react since they have high mobility on all classes plus a wallhack.

Humans also have the wallhack with the radar. As for mobility, humans can go in places advanced marauders and bigger can't, due to their size and crouching.
A pretty good example of that is yocto's alien base: there's a stair in there,  under which _battlesuits_ can go, but tyrants can not. Adv goons can, but it's trickier than for a BSuit.

> I would say that humans have a lot of useful tools to make up for this and stronger base defense structures are certainly one of them.

Currently, human's stronger stronger weapon can one-shot adv. goons from afar. Tyrants can't one-shot a medium armor, even in melee.
But that global balance thing is another topic.

> If you find that the hive in particular is too weak or niche, that would be a better problem to discuss in my opinion.

Someone in IRC said, today: "for what it's worth, hives have always been useless since trem days".

My personal problem is that a tier1 defense is strong enough to repel tier3 attackers on the human side, while tier3 alien weapons are barely able to do anything against tier0 humans.

Continuing on the mobility thing, yesterday I found an abandoned game on the `urbanp` map. As a dretch, I dodged the stream or rockets by going under them, but they were still able to do a 180° rotation and hit me 1s later. Compared to rockets, which a walking human can almost dodge without noticing them...

**Comment by Viech** [comment]
What I'm saying is: Teams are fundamentally different and the assumption that rocket pods are relatively stronger than hives (if you can even reasonably compare the two) is not a problem as such. In particular the two don't need to be balanced against each other because they don't interact. So when you are saying:

> My personal problem is that a tier1 defense is strong enough to repel tier3 attackers on the human side, while tier3 alien weapons are barely able to do anything against tier0 humans.

Then I'm happy to take arguments for why higher tier aliens have too much of a hard time against the rocket pod and I'm also open to discuss any issues of the hive being not sufficient for late game base defense but the comparison in itself I don't see much value in.

> I'm curious here, could you elaborate on that "low anti-structure damage" thingy?

I said that for _half of their weapons_. Painsaw, Flamer, Lucifer, potentially Pulse are obviously good at clearing bases. The more combat-oriented weapons not so much, you need a few seconds to kill one structure with them. Marauder and Dragoon are much faster in wrecking havoc, I think, and this is balanced by base defenses also killing them more quickly if those are not disabled first.

**Comment by Gireen** [comment]
I think rocked pod and hive individually could need some changes, but as already said there is no direct relationship between this two buildings. So there is no problem if they are not equal.
